# 拳击选手模拟器 - 配置文件

# 游戏基本信息
[game]
name = "拳击选手模拟器"
version = "1.0.0"

# 玩家初始属性
[player]
initial_health = 100
initial_stamina = 50
initial_strength = 10
initial_speed = 10
initial_defense = 5

# 游戏难度设置
# level: 1=简单, 2=普通, 3=困难, 4=专家
difficulty = { level = 2, enemy_damage_multiplier = 1.0, enemy_health_multiplier = 1.0 }

# 战斗系统设置
[combat]
critical_hit_chance = 0.1
critical_hit_multiplier = 1.5
stamina_regeneration_rate = 2

# 训练系统设置
[training]
basic_training_effect = 1.2
avanced_training_effect = 1.5
training_cost = 10
recovery_time = 3

# 比赛设置
[match]
basic_reward = 50
win_bonus = 100
title_match_reward = 500
challenge_cooldown = 10

# 商店设置
[shop]
health_potion_cost = 20
health_potion_effect = 30
stamina_potion_cost = 15
stamina_potion_effect = 20
equipment_upgrade_cost = 100